export const WITHDRAW_LIMIT_FETCH_REMAINS = 'withdraw-limit/FETCH_REMAINS';
export const WITHDRAW_LIMIT_FETCH_REMAINS_DATA = 'withdraw-limit/FETCH_REMAINS_DATA';
export const WITHDRAW_LIMIT_CHECKING = 'withdraw-limit/FETCH_CHECKING';
export const WITHDRAW_LIMIT_CHECKING_RESPONSE = 'withdraw-limit/CHECKING_RESPONSE';
export const WITHDRAW_LIMIT_CHECKING_ERROR = 'withdraw-limit/CHECKING_ERROR';
